name: Run vitest on commit

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run vitest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run vitest
        run: yarn vitest
        env:
          VITE_TESTS_NOTION_SECRET_TOKEN: ${{ secrets.VITE_TESTS_NOTION_SECRET_TOKEN }}
          VITE_TESTS_NOTION_DATABASE_1: ${{ secrets.VITE_TESTS_NOTION_DATABASE_1 }}
          VITE_TESTS_IS_GETHUB_ACTIONS: ${{ secrets.actions }}